vich_uploader:
    db_driver: orm

    mappings:
       posts:
           uri_prefix: '%post_featured_images%'
           upload_destination: '%kernel.project_dir%/public%post_featured_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

