vich_uploader:
    db_driver: orm

    mappings:
       posts:
           uri_prefix: '%post_featured_images%'
           upload_destination: '%kernel.project_dir%/assets/images/articles/%post_featured_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       paragraphs:
           uri_prefix: '%paragraph_featured_images%'
           upload_destination: '%kernel.project_dir%/assets/images/articles/%paragraph_featured_images%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer


